[package]
name = "skaffold-test"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
tokio = { version = "1.0", features = ["full"] }
tower = "0.5"
serde = { version = "1.0", features = ["derive"] }
