apiVersion: skaffold/v4beta8
kind: Config
build:
  local:
    push: false # Don't push to registry, keep images local
  artifacts:
  - image: my-image # <-- No tag here, Skaffold manages tags automatically
    custom:
      buildCommand: |
        nixpacks build . -n my-image -t latest
      dependencies:
        paths:
          - . # Watch all files in the current directory
manifests:
  rawYaml:
  - k8s/*.yaml
deploy:
  kubectl: {} # Or helm, kustomize, etc.