apiVersion: skaffold/v4beta8
kind: Config
build:
  local:
    push: false # Don't push to registry, keep images local
  artifacts:
  - image: my-image # <-- No tag here, Skaffold manages tags automatically
    custom:
      buildCommand: |
        nixpacks build . --name "$IMAGE"
      dependencies:
        paths:
          - . # Watch all files in the current directory
manifests:
  rawYaml:
  - k8s/deployment.yaml # Your Kubernetes deployment manifest
  - k8s/service.yaml # Your Kubernetes service manifest
  - k8s/ingress.yaml # Your Kubernetes ingress manifest
deploy:
  kubectl: {} # Or helm, kustomize, etc.